services:
  redis:
    image: "redis:latest"
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-somepassword}
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${REDIS_PASSWORD:-somepassword}",
      ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
