apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqukin-stage
  namespace: aqukin-stage
  labels:
    app: aqukin-stage
spec:
  selector:
    matchLabels:
      app: aqukin-stage
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aqukin-stage
    spec:
      containers:
      - name: aqukin-stage
        image: vincentbuiwork/aqukin:stage
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.5
            memory: 500M
          limits:
            cpu: 2
            memory: 2Gi
        livenessProbe:
          tcpSocket:
            port: 82
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 82
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 82
      restartPolicy: Always
